
[functions.hello]
enabled = true
verify_jwt = true
import_map = "./functions/hello/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/hello/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/hello/*.html" ]

[functions.ai-gateway]
enabled = true
verify_jwt = false
# Using default runtime imports from jsr:@supabase/functions
# No import_map needed for this function
entrypoint = "./functions/ai-gateway/index.ts"
